apiVersion: v1
kind: {{ .Values.manifestKind }}
metadata:
  name: {{ .Values.manifestKind }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}