apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.manifestName }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.appImage }}:{{ .Values.appImageTag }}"
          command: ["python", "manage.py", "migrate"]
          env:
          {{- range .Values.containerEnvVars }}
          - name: {{ .name }}
            value: {{ .value | quote  }}
          {{- end}}
      restartPolicy: Never
  backoffLimit: 2
