manifestKind: Deployment
manifestName: Manifest
appName: servicename
appImage: image_repository
appImageTag: image_tag
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"

servicePort: 8080
serviceType: ClusterIP


