version: '3.8'

services:
  testapp-database:
    image: postgres:12
    container_name: testapp-database
    env_file:
      - ./postgres-vars.env
    ports:
      - "5432:5432"
    networks:
      - testapp-network
  
  testapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./django-vars.env
    entrypoint: ./entrypoint.sh
    ##container_name: testapp-backend
    ports:
      - "8000:8000"
    depends_on:
      - testapp-database
    networks:
      - testapp-network

networks:
  testapp-network:
    driver: bridge
