apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migration-manifest
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      containers:
        - name: backend-migration
          image: bernaa77/craftech-backend-app:latest
          command: ["python", "manage.py", "migrate"]
          env:
            - name: SECRET_KEY
              value: kKZTp39JgXXe4kcp
            - name: ALLOWED_HOSTS
              value: "['*']"
            - name: SQL_ENGINE
              value: django.db.backends.postgresql
            - name: SQL_DATABASE
              value: testapp-db
            - name: SQL_USER
              value: admin
            - name: SQL_PASSWORD
              value: "12345678"
            - name: SQL_HOST
              value: testapp-db-service
            - name: SQL_PORT
              value: "5432"
            - name: RUNSERVER_PORT
              value: "8000"
      restartPolicy: Never
  backoffLimit: 2